"""Add type of Contract

Revision ID: 39d8c23e8eef
Revises: f6a47f3131df
Create Date: 2023-04-20 13:09:56.183334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39d8c23e8eef'
down_revision = 'f6a47f3131df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('type', sa.Enum('main', 'addition', name='contracttypes'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'type')
    # ### end Alembic commands ###
