"""Rename to just names in Contract, Position & Award

Revision ID: 55026979b265
Revises: 9dbedd77b2de
Create Date: 2023-05-11 00:47:40.099876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55026979b265'
down_revision = '9dbedd77b2de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('awards & penalties', sa.Column('name', sa.String(length=250), nullable=True))
    op.drop_column('awards & penalties', 'name_award')
    op.add_column('contracts', sa.Column('name', sa.String(length=250), nullable=True))
    op.drop_column('contracts', 'id_contract')
    op.add_column('positions', sa.Column('name', sa.String(length=250), nullable=True))
    op.drop_column('positions', 'name_position')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('name_position', sa.VARCHAR(length=250), nullable=True))
    op.drop_column('positions', 'name')
    op.add_column('contracts', sa.Column('id_contract', sa.VARCHAR(length=250), nullable=True))
    op.drop_column('contracts', 'name')
    op.add_column('awards & penalties', sa.Column('name_award', sa.VARCHAR(length=250), nullable=True))
    op.drop_column('awards & penalties', 'name')
    # ### end Alembic commands ###
