"""Add Position to Contracts additional table & restructorize connection of Position & Contract logic

Revision ID: c831c188d779
Revises: 39d8c23e8eef
Create Date: 2023-04-20 14:41:49.833760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c831c188d779'
down_revision = '39d8c23e8eef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'id_contract')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('id_contract', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
