"""Rename sum to cost

Revision ID: ddaf2df83236
Revises: ccc634447d7b
Create Date: 2023-04-30 19:16:45.684333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddaf2df83236'
down_revision = 'ccc634447d7b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('awards & penalties', sa.Column('cost', sa.Float(), nullable=False))
    op.drop_column('awards & penalties', 'sum')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('awards & penalties', sa.Column('sum', sa.FLOAT(), nullable=False))
    op.drop_column('awards & penalties', 'cost')
    # ### end Alembic commands ###
