"""Add AwardEvent table & restructorize Award table to list of awards

Revision ID: f6a47f3131df
Revises: f1d9d8ca3649
Create Date: 2023-04-20 13:05:25.127750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6a47f3131df'
down_revision = 'f1d9d8ca3649'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('awards & penalties', 'id_employee')
    op.drop_column('awards & penalties', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('awards & penalties', sa.Column('date', sa.DATE(), nullable=False))
    op.add_column('awards & penalties', sa.Column('id_employee', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
